---
swagger: '2.0'
info:
  description: 'API Documentation'
host: 'localhost:8080'
tags:
schemes:
- https
- http
paths:
  "/":
    get:
      tags:
      - index
      summary: index
      description: platform test
      operationId: index
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid status value
