version: "3.3"
services:
  platform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: platform
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "9229:9229"
    networks:
      - backend
    env_file:
      - .env

networks:
  backend: